# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Card.delete_all
Plate.delete_all
Card.create(image: 'train.svg', caption: 'Train', center_icon: false)
Card.create(image: 'carry-on.svg', caption: 'Carry-On Luggage', center_icon: false)
Card.create(image: 'escalator.svg', caption: 'Escalator', center_icon: false )
Card.create(image: 'flight-attendant.svg', caption: 'Flight Attendant', center_icon: false)
Card.create(image: 'ground-crew.svg', caption: 'Ground Crew', center_icon: false)
Card.create(image: 'coffee-cup.svg', caption: 'Coffee Cup', center_icon: false)
Card.create(image: 'metal-detector.svg', caption: 'Metal Detector', center_icon: false)
Card.create(image: 'people-mover.svg', caption: 'People Mover', center_icon: false)
Card.create(image: 'person-wand.svg', caption: 'Person Being Wanded', center_icon: false)
Card.create(image: 'pilot.svg', caption: 'Pilot', center_icon: false)
Card.create(image: 'police-officer.svg', caption: 'Police Officer', center_icon: false)
Card.create(image: 'take-off.svg', caption: 'Plane Taking Off', center_icon: false)
Card.create(image: 'tower.svg', caption: 'Tower', center_icon: false)
Card.create(image: 'baby.svg', caption: 'Baby', center_icon: false)
Card.create(image: 'person-laptop.svg', caption: 'Person Using Laptop', center_icon: false)
Card.create(image: 'taxi.svg', caption: 'Taxi', center_icon: false)
Card.create(image: 'passport.svg', caption: 'Passport', center_icon: false)
Card.create(image: 'newspaper.svg', caption: 'Newspaper', center_icon: false)
Card.create(image: 'police-dog.svg', caption: 'Police Dog', center_icon: false)
Card.create(image: 'jetway.svg', caption: 'Jetway', center_icon: false )
Card.create(image: 'people-eating.svg', caption: 'People Eating', center_icon: false)
Card.create(image: 'plane-ticket.svg', caption: 'Plane Ticket', center_icon: false)
Card.create(image: 'baby-bottle.svg', caption: 'Baby Bottle', center_icon: false)
Card.create(image: 'person-sleeping.svg', caption: 'Person Sleeping', center_icon: false)
Card.create(image: 'flowers.svg', caption: 'Flowers', center_icon: false)
Plate.create(image: 'dc.png', caption: 'District of Columbia')
Plate.create(image: 'florida.png', caption: 'Florida')
Plate.create(image: 'north-carolina.png', caption: 'North Carolina')
Plate.create(image: 'maine.png', caption: 'Maine')
Plate.create(image: 'montana.png', caption: 'Montana')
Plate.create(image: 'north-dakota.png', caption: 'North Dakota')
Plate.create(image: 'connecticut.png', caption: 'Connecticut')
Plate.create(image: 'south-dakota.png', caption: 'South Dakota')
Plate.create(image: 'maryland.png', caption: 'Maryland')
Plate.create(image: 'wyoming.png', caption: 'Wyoming')
Plate.create(image: 'rhode-island.png', caption: 'Rhode Island')
Plate.create(image: 'virginia.png', caption: 'Virginia')
Plate.create(image: 'new-york.png', caption: 'New York')
Plate.create(image: 'new-jersey.png', caption: 'New Jersey')
Plate.create(image: 'pennsylvania.png', caption: 'Pennsylvania')
Plate.create(image: 'massachusetts.png', caption: 'Massachusetts')
Plate.create(image: 'new-hampshire.png', caption: 'New Hampshire')
Plate.create(image: 'deleware.png', caption: 'Deleware')
Plate.create(image: 'vermont.png', caption: 'Vermont')
Plate.create(image: 'ohio.png', caption: 'ohio')
Plate.create(image: 'georgia.png', caption: 'Georgia')
Plate.create(image: 'south-carolina.png', caption: 'South Carolina')
Plate.create(image: 'west-virginia.png', caption: 'West Virginia')
Plate.create(image: 'kentucky.png', caption: 'Kentucky')
Plate.create(image: 'texas.png', caption: 'Texas')